[project]
name = "simple-pipeline"
version = "1.1.0"
description = "Pipeline to process csv file data and deliver it into another csv file"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
]
